apiVersion: v1
kind: Namespace
metadata:
    name: flask-app
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: flask-app
  namespace: test
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flask-app
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: lil00/fkproject:14
        ports:
        - containerPort: 5000
        securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: test
  labels:
    app: flask-app
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-app
  type: ClusterIP
